### ISSUE TITLE
quandry

### ISSUE THREAD

**Issue by JimmyMartin** [jonasatgit/updatereporting#12]
riddle me this batman!

The issue or compliance in a citrix pvs heavy scenario skewing compliance toward the unknown due to supercedence of cumulative update and superceded updates no longer being scanned for compliance...  How in the world do you get around this?  I want to be able to look a month back on cumulative status but once a pvs gold is patched, and the children are rebooted to the new gold, i can no longer show compliance for the previous month's cumulative.  It has me wondering if i need to start start reporting via qfe in hw inv...

**Comment by jonasatgit** [comment]
I usually only validate and report on the master image and don't care much about the cloned children. From a reporting standpoint looking back one month if the current cumulative rollup is installed does not make much sense from my point of view. Since the update is cumulative and contains the previous fixes. That's why in my report solution I set the last cumulative rollup state to installed in case the current cumulative rollup is installed. 
I do use QFE in the solution due to missing installation time in ConfigMgr. But that's the only reason. 
QFE does not help you report on historic data, since every time a new cumulative rollup installs successfully, the previous cumulative rollup entry will be deleted. 
If you really need historic data on cumulative updates, it might be worth looking into ConfigMgr Data Warehouse or a custom solution to export the required data on a schedule. 
The main question is, why look one month back if the system has the latest cumulative update installed? 
Hope it makes sense and helps you. 
Best regards
Jonas

**Comment by JimmyMartin** [comment]
True...  ty for the response
