### ISSUE TITLE
MonthSince Last Update Install shows 999

### ISSUE THREAD

**Issue by coreworx** [jonasatgit/updatereporting#13]
Moin Moin!

I just imported your reports and ran them.
There seems to be an issue with the "MonthSince Last Update Install" data.
In my environment it shows '999'.

Regards

**Comment by coreworx** [comment]
999 for all machines.

**Comment by jonasatgit** [comment]
This is probably an issue due to missing hardware inventory of class win32_quickfixengineering. Just enable the class in the client settings and check all the available properties. Note: I will limit the properties in a future relaase to just HotfixID and InstalledOn .
See key facts for more details about it: 
https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/mastering-configuration-manager-patch-compliance-reporting/ba-p/1415088#KeyFacts
Best regards
Jonas
